--Trigger que gera log da tabela PRC_PARCEIRO uma tabela de parceiros
CREATE OR REPLACE TRIGGER LOG_PARCEIRO
BEFORE UPDATE ON PRC_PARCEIRO
FOR EACH ROW

BEGIN
  DECLARE
--CÓDIGO DO PARCEIRO QUE ESTÁ SENDO ALTERADO
  ID_PARC INT(10) := :OLD.ID_PARC;
    BEGIN
          --SE O NOVO VALOR DO CAMPO FOR DIFERENTE DO VALOR ANTERIOR É INSERIDO A ALTERAÇÃO NA TABELA DE LOG LOG_PARC
         IF :NEW.PARC_CGC_ <> :OLD.PARC_CGC_ THEN
            INSERT INTO LOG_PARC(CAMPO,VALOR_ANTIGO,VALOR_NOVO,ID_REGISTRO,ID_USU_ALT,DT_ALTER)
                VALUES ('PARC_CGC_',:OLD.PARC_CGC_,:NEW.PARC_CGC_,ID_PARC,:NEW.USU_ALTER,SYSDATE);
         END IF;

         IF :NEW.ID_CIDADE <> :OLD.ID_CIDADE THEN
            INSERT INTO LOG_PARC(CAMPO,VALOR_ANTIGO,VALOR_NOVO,ID_REGISTRO,ID_USU_ALT,DT_ALTER)
                VALUES ('ID_CIDADE',:OLD.ID_CIDADE,:NEW.ID_CIDADE,ID_PARC,:NEW.USU_ALTER,SYSDATE);
         END IF;

         IF :NEW.PARC_TEL_2 <> :OLD.PARC_TEL_2 THEN
            INSERT INTO LOG_PARC(CAMPO,VALOR_ANTIGO,VALOR_NOVO,ID_REGISTRO,ID_USU_ALT,DT_ALTER)
                VALUES ('PARC_TEL_2',:OLD.PARC_TEL_2,:NEW.PARC_TEL_2,ID_PARC,:NEW.USU_ALTER,SYSDATE);
         END IF;

         IF :NEW.UF <> :OLD.UF THEN
            INSERT INTO LOG_PARC(CAMPO,VALOR_ANTIGO,VALOR_NOVO,ID_REGISTRO,ID_USU_ALT,DT_ALTER)
                VALUES ('UF',:OLD.UF,:NEW.UF,ID_PARC,:NEW.USU_ALTER,SYSDATE);
         END IF;

         IF :NEW.PARC_LOGRA <> :OLD.PARC_LOGRA THEN
            INSERT INTO LOG_PARC(CAMPO,VALOR_ANTIGO,VALOR_NOVO,ID_REGISTRO,ID_USU_ALT,DT_ALTER)
                VALUES ('PARC_LOGRA',:OLD.PARC_LOGRA,:NEW.PARC_LOGRA,ID_PARC,:NEW.USU_ALTER,SYSDATE);
         END IF;

                  IF :NEW.PARC_NUM <> :OLD.PARC_NUM THEN
            INSERT INTO LOG_PARC(CAMPO,VALOR_ANTIGO,VALOR_NOVO,ID_REGISTRO,ID_USU_ALT,DT_ALTER)
                VALUES ('PARC_NUM',:OLD.PARC_NUM,:NEW.PARC_NUM,ID_PARC,:NEW.USU_ALTER,SYSDATE);
         END IF;

                  IF :NEW.IE_RG <> :OLD.IE_RG THEN
            INSERT INTO LOG_PARC(CAMPO,VALOR_ANTIGO,VALOR_NOVO,ID_REGISTRO,ID_USU_ALT,DT_ALTER)
                VALUES ('IE_RG',:OLD.IE_RG,:NEW.IE_RG,ID_PARC,:NEW.USU_ALTER,SYSDATE);
         END IF;

                  IF :NEW.PARC_COMP <> :OLD.PARC_COMP THEN
            INSERT INTO LOG_PARC(CAMPO,VALOR_ANTIGO,VALOR_NOVO,ID_REGISTRO,ID_USU_ALT,DT_ALTER)
                VALUES ('PARC_COMP',:OLD.PARC_COMP,:NEW.PARC_COMP,ID_PARC,:NEW.USU_ALTER,SYSDATE);
         END IF;
                  IF :NEW.PARC_BAIRRO <> :OLD.PARC_BAIRRO THEN
            INSERT INTO LOG_PARC(CAMPO,VALOR_ANTIGO,VALOR_NOVO,ID_REGISTRO,ID_USU_ALT,DT_ALTER)
                VALUES ('PARC_BAIRRO',:OLD.PARC_BAIRRO,:NEW.PARC_BAIRRO,ID_PARC,:NEW.USU_ALTER,SYSDATE);
         END IF;
                  IF :NEW.PARC_TRABALHO_N <> :OLD.PARC_TRABALHO_N THEN
            INSERT INTO LOG_PARC(CAMPO,VALOR_ANTIGO,VALOR_NOVO,ID_REGISTRO,ID_USU_ALT,DT_ALTER)
                VALUES ('PARC_TRABALHO_N',:OLD.PARC_TRABALHO_N,:NEW.PARC_TRABALHO_N,ID_PARC,:NEW.USU_ALTER,SYSDATE);
         END IF;

                  IF :NEW.PARC_CEP_T <> :OLD.PARC_CEP_T THEN
            INSERT INTO LOG_PARC(CAMPO,VALOR_ANTIGO,VALOR_NOVO,ID_REGISTRO,ID_USU_ALT,DT_ALTER)
                VALUES ('PARC_CEP_T',:OLD.PARC_CEP_T,:NEW.PARC_CEP_T,ID_PARC,:NEW.USU_ALTER,SYSDATE);
         END IF;

                  IF :NEW.PARC_BAIRRO_T <> :OLD.PARC_BAIRRO_T THEN
            INSERT INTO LOG_PARC(CAMPO,VALOR_ANTIGO,VALOR_NOVO,ID_REGISTRO,ID_USU_ALT,DT_ALTER)
                VALUES ('PARC_BAIRRO_T',:OLD.PARC_BAIRRO_T,:NEW.PARC_BAIRRO_T,ID_PARC,:NEW.USU_ALTER,SYSDATE);
         END IF;

                  IF :NEW.PARC_LOGRA_T <> :OLD.PARC_LOGRA_T THEN
            INSERT INTO LOG_PARC(CAMPO,VALOR_ANTIGO,VALOR_NOVO,ID_REGISTRO,ID_USU_ALT,DT_ALTER)
                VALUES ('PARC_LOGRA_T',:OLD.PARC_LOGRA_T,:NEW.PARC_LOGRA_T,ID_PARC,:NEW.USU_ALTER,SYSDATE);
         END IF;

                  IF :NEW.PARC_NUM_T <> :OLD.PARC_NUM_T THEN
            INSERT INTO LOG_PARC(CAMPO,VALOR_ANTIGO,VALOR_NOVO,ID_REGISTRO,ID_USU_ALT,DT_ALTER)
                VALUES ('PARC_NUM_T',:OLD.PARC_NUM_T,:NEW.PARC_NUM_T,ID_PARC,:NEW.USU_ALTER,SYSDATE);
         END IF;

                  IF :NEW.PARC_COMP_T <> :OLD.PARC_COMP_T THEN
            INSERT INTO LOG_PARC(CAMPO,VALOR_ANTIGO,VALOR_NOVO,ID_REGISTRO,ID_USU_ALT,DT_ALTER)
                VALUES ('PARC_COMP_T',:OLD.PARC_COMP_T,:NEW.PARC_COMP_T,ID_PARC,:NEW.USU_ALTER,SYSDATE);
         END IF;

                           IF :NEW.PARC_TEL_T <> :OLD.PARC_TEL_T THEN
            INSERT INTO LOG_PARC(CAMPO,VALOR_ANTIGO,VALOR_NOVO,ID_REGISTRO,ID_USU_ALT,DT_ALTER)
                VALUES ('PARC_TEL_T',:OLD.PARC_TEL_T,:NEW.PARC_TEL_T,ID_PARC,:NEW.USU_ALTER,SYSDATE);
         END IF;

                           IF :NEW.PARC_SALARIO <> :OLD.PARC_SALARIO THEN
            INSERT INTO LOG_PARC(CAMPO,VALOR_ANTIGO,VALOR_NOVO,ID_REGISTRO,ID_USU_ALT,DT_ALTER)
                VALUES ('PARC_SALARIO',:OLD.PARC_SALARIO,:NEW.PARC_SALARIO,ID_PARC,:NEW.USU_ALTER,SYSDATE);
         END IF;

                           IF :NEW.PARC_ADMISSAO <> :OLD.PARC_ADMISSAO THEN
            INSERT INTO LOG_PARC(CAMPO,VALOR_ANTIGO,VALOR_NOVO,ID_REGISTRO,ID_USU_ALT,DT_ALTER)
                VALUES ('PARC_ADMISSAO',:OLD.PARC_ADMISSAO,:NEW.PARC_ADMISSAO,ID_PARC,:NEW.USU_ALTER,SYSDATE);
         END IF;

                           IF :NEW.PARC_CID_F <> :OLD.PARC_CID_F THEN
            INSERT INTO LOG_PARC(CAMPO,VALOR_ANTIGO,VALOR_NOVO,ID_REGISTRO,ID_USU_ALT,DT_ALTER)
                VALUES ('PARC_CID_F',:OLD.PARC_CID_F,:NEW.PARC_CID_F,ID_PARC,:NEW.USU_ALTER,SYSDATE);
         END IF;

                           IF :NEW.PARC_NOME <> :OLD.PARC_NOME THEN
            INSERT INTO LOG_PARC(CAMPO,VALOR_ANTIGO,VALOR_NOVO,ID_REGISTRO,ID_USU_ALT,DT_ALTER)
                VALUES ('PARC_NOME',:OLD.PARC_NOME,:NEW.PARC_NOME,ID_PARC,:NEW.USU_ALTER,SYSDATE);
         END IF;

                           IF :NEW.PARC_N_RAZAO_SOCIAL <> :OLD.PARC_N_RAZAO_SOCIAL THEN
            INSERT INTO LOG_PARC(CAMPO,VALOR_ANTIGO,VALOR_NOVO,ID_REGISTRO,ID_USU_ALT,DT_ALTER)
                VALUES ('PARC_N_RAZAO_SOCIAL',:OLD.PARC_N_RAZAO_SOCIAL,:NEW.PARC_N_RAZAO_SOCIAL,ID_PARC,:NEW.USU_ALTER,SYSDATE);
         END IF;

                           IF :NEW.PARC_STATUS <> :OLD.PARC_STATUS THEN
            INSERT INTO LOG_PARC(CAMPO,VALOR_ANTIGO,VALOR_NOVO,ID_REGISTRO,ID_USU_ALT,DT_ALTER)
                VALUES ('PARC_STATUS',:OLD.PARC_STATUS,:NEW.PARC_STATUS,ID_PARC,:NEW.USU_ALTER,SYSDATE);
         END IF;

                           IF :NEW.PARC_FORNEC <> :OLD.PARC_FORNEC THEN
            INSERT INTO LOG_PARC(CAMPO,VALOR_ANTIGO,VALOR_NOVO,ID_REGISTRO,ID_USU_ALT,DT_ALTER)
                VALUES ('PARC_FORNEC',:OLD.PARC_FORNEC,:NEW.PARC_FORNEC,ID_PARC,:NEW.USU_ALTER,SYSDATE);
         END IF;

                           IF :NEW.PARC_USU <> :OLD.PARC_USU THEN
            INSERT INTO LOG_PARC(CAMPO,VALOR_ANTIGO,VALOR_NOVO,ID_REGISTRO,ID_USU_ALT,DT_ALTER)
                VALUES ('PARC_USU',:OLD.PARC_USU,:NEW.PARC_USU,ID_PARC,:NEW.USU_ALTER,SYSDATE);
         END IF;

                       IF :NEW.PARC_TEL <> :OLD.PARC_TEL THEN
            INSERT INTO LOG_PARC(CAMPO,VALOR_ANTIGO,VALOR_NOVO,ID_REGISTRO,ID_USU_ALT,DT_ALTER)
                VALUES ('PARC_TEL',:OLD.PARC_TEL,:NEW.PARC_TEL,ID_PARC,:NEW.USU_ALTER,SYSDATE);
         END IF;

                                IF :NEW.PARC_EMAIL <> :OLD.PARC_EMAIL THEN
            INSERT INTO LOG_PARC(CAMPO,VALOR_ANTIGO,VALOR_NOVO,ID_REGISTRO,ID_USU_ALT,DT_ALTER)
                VALUES ('PARC_EMAIL',:OLD.PARC_EMAIL,:NEW.PARC_EMAIL,ID_PARC,:NEW.USU_ALTER,SYSDATE);
         END IF;

                                IF :NEW.PARC_CEP <> :OLD.PARC_CEP THEN
            INSERT INTO LOG_PARC(CAMPO,VALOR_ANTIGO,VALOR_NOVO,ID_REGISTRO,ID_USU_ALT,DT_ALTER)
                VALUES ('PARC_CEP',:OLD.PARC_CEP,:NEW.PARC_CEP,ID_PARC,:NEW.USU_ALTER,SYSDATE);
         END IF;

                               IF :NEW.PARC_OBS <> :OLD.PARC_OBS THEN
            INSERT INTO LOG_PARC(CAMPO,VALOR_ANTIGO,VALOR_NOVO,ID_REGISTRO,ID_USU_ALT,DT_ALTER)
                VALUES ('PARC_OBS',:OLD.PARC_OBS,:NEW.PARC_OBS,ID_PARC,:NEW.USU_ALTER,SYSDATE);
         END IF;

                                IF :NEW.PARC_BLOQUEADO <> :OLD.PARC_BLOQUEADO THEN
            INSERT INTO LOG_PARC(CAMPO,VALOR_ANTIGO,VALOR_NOVO,ID_REGISTRO,ID_USU_ALT,DT_ALTER)
                VALUES ('PARC_BLOQUEADO',:OLD.PARC_BLOQUEADO,:NEW.PARC_BLOQUEADO,ID_PARC,:NEW.USU_ALTER,SYSDATE);
         END IF;

                                IF :NEW.PARC_NASC <> :OLD.PARC_NASC THEN
            INSERT INTO LOG_PARC(CAMPO,VALOR_ANTIGO,VALOR_NOVO,ID_REGISTRO,ID_USU_ALT,DT_ALTER)
                VALUES ('PARC_NASC',:OLD.PARC_NASC,:NEW.PARC_NASC,ID_PARC,:NEW.USU_ALTER,SYSDATE);
         END IF;
   END;
END;
